version: '3.8'
services:
  stocks_db:
    image: postgres:15-alpine
    container_name: itapia-stocks_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - itapia-network

  data-processor:
    build:
      context: ./data_processing
    container_name: itapia-data-processor
    env_file:
      - .env
    volumes:
      - ./data_processing:/app
    depends_on:
      - stocks_db
    networks:
      - itapia-network
  
volumes:
  postgres_data:

networks:
  itapia-network:
    driver: bridge