version: '3.8'
services:
  stocks_postgre_db:
    image: postgres:15-alpine
    container_name: itapia-stocks_postgre_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - itapia-network

  realtime_db:
    image: redis:7-alpine
    container_name: itapia-redis_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - itapia-network

  batch-data-processor:
    image: itapia-data-processor:latest
    container_name: itapia-batch-data-processor
    env_file:
      - .env
    volumes:
      - ./data_processing:/app
    depends_on:
      - stocks_postgre_db
    networks:
      - itapia-network

  realtime-data-processor:
    image: itapia-data-processor:latest
    restart: always 
    container_name: itapia-realtime-data-processor
    env_file:
      - .env
    depends_on:
      - realtime_db
    networks:
      - itapia-network
    # Chạy script điều phối real-time
    command: python -u scripts/fetch_realtime_price.py
  
  api-service:
    image: itapia-api-service:latest
    restart: unless-stopped
    container_name: itapia-api-service
    env_file:
      - .env
    depends_on:
      - realtime_db
      - stocks_postgre_db
    ports:
      - "8000:8000"
    networks:
      - itapia-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
volumes:
  postgres_data:

networks:
  itapia-network:
    driver: bridge