# version: '3.8'
services:
  stocks_postgre_db:
    image: postgres:15-alpine
    container_name: itapia-stocks_postgre_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - itapia-network

  realtime_redis_db:
    image: redis:7-alpine
    container_name: itapia-redis_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - itapia-network

  batch-data-processor:
    image: itapia-data-processor:latest
    container_name: itapia-batch-data-processor
    env_file:
      - .env
    volumes:
      - ./data_processing:/data-processing
    depends_on:
      - stocks_postgre_db
    networks:
      - itapia-network

  realtime-data-processor:
    image: itapia-data-processor:latest
    restart: always 
    container_name: itapia-realtime-data-processor
    env_file:
      - .env
    depends_on:
      - realtime_redis_db
      - stocks_postgre_db
    networks:
      - itapia-network
    volumes:
      - ./data_processing:/data-processing
    # Chạy script điều phối real-time
    command: python -m scripts.fetch_realtime_prices

  data-seeds:
    image: itapia-data-seeds:latest
    container_name: itapia-data-seeds
    env_file:
      - .env
    depends_on:
      - stocks_postgre_db
    volumes:
      - ./data_seeds:/data-seeds
    networks:
      - itapia-network

  
  api-gateway:
    image: itapia-api-gateway:latest
    restart: unless-stopped
    container_name: itapia-api-gateway
    env_file:
      - .env
    depends_on:
      - realtime_redis_db
      - stocks_postgre_db
      - ai-service-quick
    volumes:
      - ./api_gateway:/api-gateway
    ports:
      - "8000:8000"
    networks:
      - itapia-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ai-service-quick:
    image: itapia-ai-service-quick:latest
    restart: unless-stopped
    container_name: itapia-ai-service-quick
    env_file:
      - .env
    volumes:
      - ./ai_service_quick/app:/ai-service-quick/app
      - ai_service_quick_kaggle_cache:/root/.cache/kagglehub
      - ai_service_quick_hgf_cache:/root/.cache/huggingface
    depends_on:
      - realtime_redis_db
      - stocks_postgre_db
    ports:
      - "8001:8000"
    networks:
      - itapia-network
    entrypoint: /ai-service-quick/entrypoint.sh

volumes:
  # KHAI BÁO VOLUME LÀ EXTERNAL
  postgres_data:
    external: true
    name: itapia_postgres_data # Chỉ định tên thật của volume đang tồn tại trong Docker
  
  redis_data:
    external: true
    name: itapia_redis_data # Làm tương tự cho redis
    
  ai_service_quick_kaggle_cache:
    external: true
    name: itapia_ai_service_quick_kaggle_cache # Và cho các cache

  ai_service_quick_hgf_cache:
    external: true
    name: itapia_ai_service_quick_hgf_cache

networks:
  itapia-network:
    driver: bridge