# Module này để tiện lợi trong quá trình gọi biến, ko phải truyền qua string
# Các biến trong này ko chắc là sẽ được đăng ký, muốn xem các biến được đăng ký thì qua registry.py

# 1. Constant

# Format num template
CONST_NUM_TEMPLATE = 'CONST_NUM_{sign_char}{name}'
def CONST_NUM(value: float):
    sign_char = "P" if value >= 0 else "N"
    name_str = str(abs(value)).replace('.', '_')
    return CONST_NUM_TEMPLATE.format(sign_char=sign_char, name=name_str)

CONST_RSI_OVERBOUGHT = 'CONST_RSI_OVERBOUGHT'
CONST_RSI_OVERSOLD = 'CONST_RSI_OVERSOLD'
CONST_STOCH_OVERBOUGHT = 'CONST_STOCH_OVERBOUGHT'
CONST_STOCH_OVERSOLD = 'CONST_STOCH_OVERSOLD'
CONST_ADX_STRONG_TREND = 'CONST_ADX_STRONG_TREND'

# Threshold
THRESHOLD_DECISION_BUY_IMMEDIATE = 'THRESHOLD_DECISION_BUY_IMMEDIATE'
THRESHOLD_DECISION_BUY_STRONG = 'THRESHOLD_DECISION_BUY_STRONG'
THRESHOLD_DECISION_BUY_MODERATE = 'THRESHOLD_DECISION_BUY_MODERATE'
THRESHOLD_DECISION_ACCUMULATE = 'THRESHOLD_DECISION_ACCUMULATE'
THRESHOLD_DECISION_HOLD_NEUTRAL = 'THRESHOLD_DECISION_HOLD_NEUTRAL'
THRESHOLD_DECISION_HOLD_POSITIVE = 'THRESHOLD_DECISION_HOLD_POSITIVE'
THRESHOLD_DECISION_HOLD_NEGATIVE = 'THRESHOLD_DECISION_HOLD_NEGATIVE'
THRESHOLD_DECISION_REDUCE_POSITION = 'THRESHOLD_DECISION_REDUCE_POSITION'
THRESHOLD_DECISION_SELL_MODERATE = 'THRESHOLD_DECISION_SELL_MODERATE'
THRESHOLD_DECISION_SELL_STRONG = 'THRESHOLD_DECISION_SELL_STRONG'
THRESHOLD_DECISION_SELL_IMMEDIATE = 'THRESHOLD_DECISION_SELL_IMMEDIATE'

THRESHOLD_RISK_VERY_LOW = 'THRESHOLD_RISK_VERY_LOW'
THRESHOLD_RISK_LOW = 'THRESHOLD_RISK_LOW'
THRESHOLD_RISK_MODERATE = 'THRESHOLD_RISK_MODERATE'
THRESHOLD_RISK_HIGH = 'THRESHOLD_RISK_HIGH'
THRESHOLD_RISK_VERY_HIGH = 'THRESHOLD_RISK_VERY_HIGH'

THRESHOLD_OPP_RATING_TOP_TIER = 'THRESHOLD_OPP_RATING_TOP_TIER'
THRESHOLD_OPP_RATING_STRONG = 'THRESHOLD_OPP_RATING_STRONG'
THRESHOLD_OPP_RATING_INTERESTING = 'THRESHOLD_OPP_RATING_INTERESTING'
THRESHOLD_OPP_RATING_NEUTRAL = 'THRESHOLD_OPP_RATING_NEUTRAL'
THRESHOLD_OPP_RATING_AVOID = 'THRESHOLD_OPP_RATING_AVOID'


# 2. Var
VAR_D_RSI_14 = 'VAR_D_RSI_14'
VAR_D_ADX_14 = 'VAR_D_ADX_14'
VAR_D_ATR_14 = 'VAR_D_ATR_14'
VAR_D_TREND_MIDTERM_DIR = 'VAR_D_TREND_MIDTERM_DIR'
VAR_D_TREND_LONGTERM_DIR = 'VAR_D_TREND_LONGTERM_DIR'
VAR_D_TREND_OVERALL_STRENGTH = 'VAR_D_TREND_OVERALL_STRENGTH'
VAR_D_SUPPORT_1_PRICE = 'VAR_D_SUPPORT_1_PRICE'
VAR_D_RESISTANCE_1_PRICE = 'VAR_D_RESISTANCE_1_PRICE'
VAR_D_PATTERN_1_SCORE = 'VAR_D_PATTERN_1_SCORE'
VAR_D_PATTERN_1_SENTIMENT = 'VAR_D_PATTERN_1_SENTIMENT'
VAR_I_RSI_STATUS = 'VAR_I_RSI_STATUS'
VAR_I_MACD_CROSSOVER = 'VAR_I_MACD_CROSSOVER'
VAR_I_ORB_STATUS = 'VAR_I_ORB_STATUS'

VAR_FC_TB_PREDICTION = 'VAR_FC_TB_PREDICTION'
VAR_FC_5D_MEAN_PCT = 'VAR_FC_5D_MEAN_PCT'
VAR_FC_5D_STD_PCT = 'VAR_FC_5D_STD_PCT'
VAR_FC_5D_MAX_PCT = 'VAR_FC_5D_MAX_PCT'
VAR_FC_5D_MIN_PCT = 'VAR_FC_5D_MIN_PCT'
VAR_FC_5D_Q25_PCT = 'VAR_FC_5D_Q25_PCT'
VAR_FC_5D_Q75_PCT = 'VAR_FC_5D_Q75_PCT'
VAR_FC_20D_MEAN_PCT = 'VAR_FC_20D_MEAN_PCT'
VAR_FC_20D_STD_PCT = 'VAR_FC_20D_STD_PCT'
VAR_FC_20D_MAX_PCT = 'VAR_FC_20D_MAX_PCT'
VAR_FC_20D_MIN_PCT = 'VAR_FC_20D_MIN_PCT'

VAR_NEWS_SUM_NUM_POSITIVE = 'VAR_NEWS_SUM_NUM_POSITIVE'
VAR_NEWS_SUM_NUM_NEGATIVE = 'VAR_NEWS_SUM_NUM_NEGATIVE'
VAR_NEWS_SUM_NUM_HIGH_IMPACT = 'VAR_NEWS_SUM_NUM_HIGH_IMPACT'
VAR_NEWS_SUM_NUM_MODERATE_IMPACT = 'VAR_NEWS_SUM_NUM_MODERATE_IMPACT'
VAR_NEWS_SUM_NUM_LOW_IMPACT = 'VAR_NEWS_SUM_NUM_LOW_IMPACT'
VAR_NEWS_SUM_AVG_POSITIVE_KEYWORDS = 'VAR_NEWS_SUM_AVG_POSITIVE_KEYWORDS'
VAR_NEWS_SUM_AVG_NEGATIVE_KEYWORDS = 'VAR_NEWS_SUM_AVG_NEGATIVE_KEYWORDS'
VAR_NEWS_SUM_AVG_NER = 'VAR_NEWS_SUM_AVG_NER'


# 3. Operator
# --- A. Toán tử Toán học ---
OPR_ADD2 = 'OPR_ADD2'
OPR_SUB2 = 'OPR_SUB2'
OPR_MUL2 = 'OPR_MUL2'
OPR_DIV2 = 'OPR_DIV2'
OPR_POW2 = 'OPR_POW2'
OPR_LOG2 = 'OPR_LOG2'
OPR_ABS = 'OPR_ABS'

# --- B. Toán tử So sánh ---
OPR_GT = 'OPR_GT' # Greater Than (>)
OPR_LT = 'OPR_LT' # Less Than (<)
OPR_GTE = 'OPR_GTE' # Greater Than or Equal (>=)
OPR_LTE = 'OPR_LTE' # Less Than or Equal (<=)
OPR_EQ = 'OPR_EQ' # Equal (==)
OPR_NEQ = 'OPR_NEQ' # Not Equal (!=)

# --- C. Toán tử Logic ---
OPR_AND = 'OPR_AND'
OPR_OR = 'OPR_OR'
OPR_NOT = 'OPR_NOT'

# --- D. Toán tử Điều kiện ---
OPR_IF_THEN_ELSE = 'OPR_IF_THEN_ELSE'

# --- E. Toán tử Kết luận Đặc biệt (Return Operators) ---
OPR_TO_DECISION_SIGNAL = 'OPR_TO_DECISION_SIGNAL'
OPR_TO_RISK_LEVEL = 'OPR_TO_RISK_LEVEL'
OPR_TO_OPPORTUNITY_RATING = 'OPR_TO_OPPORTUNITY_RATING'