CREATE TABLE IF NOT EXISTS public.daily_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collect_date TIMESTAMP NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    adj_close FLOAT,
    volume FLOAT,
    
    UNIQUE (collect_date, ticker) 
);