CREATE TABLE IF NOT EXISTS public.history_prices ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "open" float4 NULL, high float4 NULL, 
    low float4 NULL, "close" float4 NULL, 
    volume float4 NULL, ticker varchar(12) NOT NULL, 
    collect_date timestamp with time zone NOT NULL, 
    CONSTRAINT history_prices_unique UNIQUE (ticker, collect_date)
);

CREATE TABLE IF NOT EXISTS public.relevant_news ( 
    news_uuid varchar(256) PRIMARY KEY,
    ticker varchar(12) not null,
    title TEXT not null,
    summary TEXT null,
    provider varchar(150) null,
    link TEXT null,
    content_type varchar(25) null,
    publish_time timestamp with time zone null,
    collect_time timestamp with time zone not null
);