/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/advisor/': RouteRecordInfo<'/advisor/', '/advisor', Record<never, never>, Record<never, never>>,
    '/advisor/[ticker]': RouteRecordInfo<'/advisor/[ticker]', '/advisor/:ticker', { ticker: ParamValue<true> }, { ticker: ParamValue<false> }>,
    '/analysis/': RouteRecordInfo<'/analysis/', '/analysis', Record<never, never>, Record<never, never>>,
    '/analysis/[ticker]': RouteRecordInfo<'/analysis/[ticker]', '/analysis/:ticker', { ticker: ParamValue<true> }, { ticker: ParamValue<false> }>,
    '/auth/google/callback': RouteRecordInfo<'/auth/google/callback', '/auth/google/callback', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profiles/': RouteRecordInfo<'/profiles/', '/profiles', Record<never, never>, Record<never, never>>,
    '/profiles/[profile_id]': RouteRecordInfo<'/profiles/[profile_id]', '/profiles/:profile_id', { profile_id: ParamValue<true> }, { profile_id: ParamValue<false> }>,
    '/rules/': RouteRecordInfo<'/rules/', '/rules', Record<never, never>, Record<never, never>>,
    '/rules/[rule_id]': RouteRecordInfo<'/rules/[rule_id]', '/rules/:rule_id', { rule_id: ParamValue<true> }, { rule_id: ParamValue<false> }>,
  }
}
